---
# tasks file for hoplacloud.linux_base_del_user

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'
